### ISSUE TITLE
Invisible Contact on Dark Variant

### ISSUE THREAD

**Issue by umahdroid** [drakkar1969/mailspring-libadwaita-theme#2]
Contact text and contents under this bar with two panel mode when using dark variant need a bit more love.

![Screenshot from 2023-02-15 11-24-21](https://user-images.githubusercontent.com/39919860/218930716-f81cff6d-3a53-4561-bc7d-d7dd06d0eb79.png)

Anyway, thanks for making this lovely theme <3

**Comment by drakkar1969** [comment]
Sorry for the really late response, I haven't had a lot of time to work on this over the last few weeks.
Styling for the user avatar, contact details and related threads in the contact sidebar now updated:

![image](https://user-images.githubusercontent.com/18715287/229276764-181247dd-e7f6-4a6c-a43b-89db85f84464.png)

**Comment by umahdroid** [comment]
Perfect 🥳 Thanks for making this theme!
