### ISSUE TITLE
Unscaled icon

### ISSUE THREAD

**Issue by spazziale** [drakkar1969/mailspring-libadwaita-theme#3]
Hi, love your theme!
I just encountered this little bug with scaling.
I'm using the flatpak version with wayland.
![image](https://github.com/drakkar1969/mailspring-libadwaita-theme/assets/46284310/db63e5cf-09e7-483d-adcb-44e3cfe16e19)

**Comment by spazziale** [comment]
restarted, now i don't have this problem

**Comment by drakkar1969** [comment]
Cool, good to know problem is fixed
