### ISSUE TITLE
Pop-up for adding hyperlinks is tiny

### ISSUE THREAD

**Issue by alizehctl** [drakkar1969/mailspring-libadwaita-theme#4]
When I press `Ctrl + K` to add a link to piece of text, the input field that pop ups is unusably smol. Also, it doesn't follow the dark theme.

![image](https://github.com/drakkar1969/mailspring-libadwaita-theme/assets/31581044/cd6514ff-a7c0-41f5-b186-358cc987d448)

**Comment by drakkar1969** [comment]
The popup not following the dark theme is definitely an issue with the theme, will take a look.

The width of the popup is however linked to the width of the window, I don't think it has anything to do with the theme (recognizing that the libadwaita theme does make buttons bigger, so the issue will happen with wider windows compared to the default themes)

**Comment by alizehctl** [comment]
I just tried inserting a link at different screen sizes, and the popup seemed to change width at random. Sometimes it would be small when the window is large, sometimes it would be normal sized when the window is small. I would send a screen recording but can't since the window has all my work emails in it.

Would it be possible to set a `min-width` on the link input? Maybe something like `min-width: 20ch`. IMO the popup should remain usable at all window sizes.

**Comment by drakkar1969** [comment]
Should be fixed with https://github.com/drakkar1969/mailspring-libadwaita-theme/commit/dbfff75ed8a7e8f4d5d4974d7fea4e7c789240a0

**Comment by alizehctl** [comment]
Thank you!
